export const CONSTANT_ROUTE = {
  HOME_PAGE: "/",
  SIGN_IN: "/signin",
  SIGN_UP: "/signup",
  LOG_OUT: "/logout",
  FORGOT_PASSWORD: "/password/forgot",
  CHANGE_PASSWORD: "/password/change",
  MANAGE_USER: "/authen/manage/user",
  MANAGE_COURSE: "/authen/manage/course",
  MANAGE_LESSON: "/authen/manage/lesson",
  MANAGE_CHAPTER: "/authen/manage/chapter",
  MANAGE_CONTACT: "/authen/manage/contact",
  MANAGE_BLOG: "/authen/manage/blog",
  MANAGE_BLOG_DETAILS: "/authen/manage/blog-details",
  MANAGE_FEEDBACK: "/authen/manage/feedback",
  MANAGE_SUPPORT: "/authen/manage/support",
  MANAGE_LESSON: "/authen/manage/lesson",
};
